# Generated by Django 3.2.15 on 2022-08-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_auto_20220807_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesas',
            options={'verbose_name': 'Despesas', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='receitas',
            options={'verbose_name': 'Receitas', 'verbose_name_plural': 'Receitas'},
        ),
    ]
